<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_15_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [1]:
import numpy as np

a= np.array([5,5,5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5, 5, 5])

In [2]:
import numpy as np

a = np.array([3,3,3,3,3])
a

array([3, 3, 3, 3, 3])

In [3]:
type(a)

numpy.ndarray

In [5]:
b = np.array([[6,6,6],[6,6,6],[6,6,6]])
b

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [7]:
len(a)


5

In [9]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [11]:
b = np.zeros(4)
b

array([0., 0., 0., 0.])

In [12]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [13]:
d = np.empty(3)
d

array([0. , 0.5, 1. ])

In [15]:
# with range of elements
e = np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
# with specific range of elements

f = np.arange(0,45)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [18]:
g = np.arange(3,30,3)
g

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [20]:
h = np.arange(2,20,2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# lineared spaced array
import numpy as np

i = np.linspace(0,10,num=4)
i

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [27]:
# specific data type

j = np.ones(6, dtype=np.int8)
j

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [29]:
k = np.ones(3, dtype=np.float64)
k

array([1., 1., 1.])

**2d arrays**

In [31]:
np.zeros((4,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
np.empty((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**3D array**

In [42]:
#  making and resHAPING OF 3D ARRAY

l = np.arange(24).reshape(2,3,4)
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])