<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_20_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris = load_iris()
phool = pd.DataFrame(data=iris.data, columns=iris.feature_names)
phool['species'] = iris.target_names[iris.target]
phool

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [3]:
import numpy as np

# Creating a simple array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Element-wise addition
result = arr1 + arr2
print(result)

[6 6 6 6 6]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_arr = arr.reshape(3, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing a specific element
print(arr[2])

# Slicing an array
print(arr[1:4])

30
[20 30 40]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Mean of the array
mean = np.mean(arr)
print(mean)

# Standard deviation
std_dev = np.std(arr)
print(std_dev)

3.0
1.4142135623730951


In [8]:
import numpy as np

# Defining two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


In [9]:
import numpy as np

# Generating random numbers
random_arr = np.random.rand(3, 3)  # Generates a 3x3 matrix with random numbers
print(random_arr)

[[0.09616611 0.65759019 0.5810141 ]
 [0.35555132 0.45415923 0.20785231]
 [0.91221424 0.99642205 0.89557294]]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([10])

# Broadcasting (adding scalar to array)
result = arr1 + arr2
print(result)

[11 12 13]


In [11]:
import numpy as np

arr = np.array([10, 20, 5, 60, 30])

# Finding max and min
max_val = np.max(arr)
min_val = np.min(arr)

print("Max Value:", max_val)
print("Min Value:", min_val)

Max Value: 60
Min Value: 5


In [12]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# Matrix Inversion
inverse_arr = np.linalg.inv(arr)
print(inverse_arr)

[[-2.   1. ]
 [ 1.5 -0.5]]
