<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_18_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a


array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

np.int64(1)

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [7]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a.ndim


2

In [10]:
a.shape
len(a.shape) == a.ndim

True

In [11]:
a.size
import math
a.size == math.prod(a.shape)

True

In [12]:
np.zeros(2)

array([0., 0.])