<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_18_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a


array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

np.int64(1)

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [7]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a.ndim


2

In [10]:
a.shape
len(a.shape) == a.ndim

True

In [11]:
a.size
import math
a.size == math.prod(a.shape)

True

In [12]:
np.zeros(2)

array([0., 0.])

In [13]:
# Create an empty array with 2 elements
np.empty(2)

array([0., 0.])

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [19]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [23]:
five_up = (a >= 5)
print(a[five_up])

[]


In [24]:
print(a[a < 5])

[1 2 3 4]


In [25]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[2 4]


In [26]:
five_up = (a > 5) | (a == 5)
print(five_up)

[False False False False]
