<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_17_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

numpy practice

In [1]:
 # import library
import numpy as np

# creating an array using numpy
food = np.array(["pakora", "samosa", "raita"])
food


array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [2]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
type(food)

numpy.ndarray

In [6]:
len(price)


3

In [10]:
len(food)

3

In [9]:
price[2]


np.str_('samosa')

In [11]:
price[0:]


array([5, 5, 5])

In [12]:
food[1]

np.str_('samosa')

In [13]:
price.mean()

np.float64(5.0)

In [14]:
# zero method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# ones method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
# empty
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
#table of 5

np.arange(5,50,5)


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
 # line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
# specify data type

np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [29]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# Array functions

a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [33]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [35]:
a.argmin()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [36]:
b=np.array([10.2,13.4,50.6,33.3,44.9,91.8])
b

array([10.2, 13.4, 50.6, 33.3, 44.9, 91.8])

In [37]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,  13.4,  50.6,  33.3,  44.9,  91.8])

In [38]:
c.sort()
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,  13.4,
        15. ,  33.3,  44.9,  50.6,  91.8, 100. , 320. ])

**2-D array**

In [40]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [44]:
b = np.array([[6,7,8,2,3],[6,5,4,1,2]])
b

array([[6, 7, 8, 2, 3],
       [6, 5, 4, 1, 2]])

In [45]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 2, 3],
       [6, 5, 4, 1, 2]])

In [47]:
c = np.concatenate((a,b) , axis=0)
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 2, 3],
       [6, 5, 4, 1, 2]])

In [48]:
c = np.concatenate((a,b) , axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 2, 3],
       [5, 4, 3, 2, 1, 6, 5, 4, 1, 2]])

In [46]:
c.sort()
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [2, 3, 6, 7, 8],
       [1, 2, 4, 5, 6]])