<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_17_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

numpy practice

In [1]:
 # import library
import numpy as np

# creating an array using numpy
food = np.array(["pakora", "samosa", "raita"])
food


array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [2]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
type(food)

numpy.ndarray

In [6]:
len(price)


3

In [10]:
len(food)

3

In [9]:
price[2]


np.str_('samosa')

In [11]:
price[0:]


array([5, 5, 5])

In [12]:
food[1]

np.str_('samosa')

In [13]:
price.mean()

np.float64(5.0)

In [14]:
# zero method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])