<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/Day_17_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

numpy practice

In [1]:
 # import library
import numpy as np

# creating an array using numpy
food = np.array(["pakora", "samosa", "raita"])
food


array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [2]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [3]:
type(price)

numpy.ndarray

In [4]:
type(food)

numpy.ndarray

In [6]:
len(price)


3

In [10]:
len(food)

3

In [9]:
price[2]


np.str_('samosa')

In [11]:
price[0:]


array([5, 5, 5])

In [12]:
food[1]

np.str_('samosa')

In [13]:
price.mean()

np.float64(5.0)

In [14]:
# zero method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# ones method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
# empty
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
#table of 5

np.arange(5,50,5)


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
 # line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
# specify data type

np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [29]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])