<a href="https://colab.research.google.com/github/ahmadzulfiqar001/python-100-days-beginner-to-advance-/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# NumPy Array
numbers = np.array([1, 2, 3, 4, 5])
print(numbers)

[1 2 3 4 5]


In [3]:
import numpy as np

a = np.array([10,20,30,40])

print(a)

[10 20 30 40]


In [4]:
import numpy as np

a = np.array([10,20,30,40])

print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(4,)
4
int64
1


In [7]:
import numpy as np

a = np.array([[1,2],
              [3,4]])

print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

[[1 2]
 [3 4]]
(2, 2)
4
int64
2


In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(2,23,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [18]:
np.random.rand(5)

array([0.4913939 , 0.18134007, 0.3032154 , 0.65870505, 0.78427225])

In [22]:
np.random.randint(1,100,100)

array([ 3,  5, 30, 96, 98, 53, 28, 89, 52, 94, 44, 89, 62, 58, 96, 10, 93,
        8, 65, 46, 72, 22, 23, 63, 86, 93, 28, 57, 23, 16,  6, 98, 40, 84,
       53, 22, 43, 34, 14, 74, 35, 56, 82, 22, 83, 68, 23, 36, 39, 79, 77,
       58, 94, 65, 88, 71, 46, 68, 87, 67, 67, 21, 79, 24, 67, 60, 32, 96,
       70, 67, 95,  1, 14, 95,  8, 24, 15, 42, 58, 84, 93, 31, 25, 93, 34,
       76, 21,  5, 44, 57, 79, 81, 36, 29, 15, 48, 51,  2, 74, 36])

In [23]:
a=np.array([10,20,30,40,50])

print(a[0])
print(a[2])
print(a[-1])

10
30
50


In [26]:
a=np.array([10,20,30,40,50])

print(a[0:3])

[10 20 30]


In [27]:
a=np.array([1,2,3])

print(a+5)

[6 7 8]


In [28]:
print(a*2)

[2 4 6]


In [29]:
print(a+2)

[3 4 5]


In [30]:
print(a**2)

[1 4 9]


In [32]:
a=np.array([23,4,56,7])
b=np.array([4,55,65,7])

print(a+b)

[ 27  59 121  14]


In [33]:
print(a*b)

[  92  220 3640   49]


In [35]:
a=np.array([10,30,50,20,70])

print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.std(a))
print(np.min(a))

180
36.0
70
21.540659228538015
10


In [41]:
a=np.arange(1,13)
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
